<a href="https://colab.research.google.com/github/s1w4e/ML_icp3/blob/main/ML_icp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a.Using Numpy create  random vector of size 15 having only Integers in the range 1-20.
  1.Reshaping the array to 3 by 5
  2.print array shape
  3.Replacing the max in each row by 0

In [ ]:
import numpy as np
#creating a random vetor
integer_array = np.random.randint(1,21,15)
print(integer_array)

#reshaping the array
reshape_array=integer_array.reshape(3,5)
print('reshape array:\n',reshape_array)

#to print the shape of array
print('shape:\n',reshape_array.shape)

# Find the index of the maximum value in each row
max_indices = np.argmax(reshape_array, axis=1)

# Set the maximum values in each row to 0
reshape_array[np.arange(reshape_array.shape[0]), max_indices] = 0
print(reshape_array)

[12 13  1 16  6  8  6  4  3  1 13 15  8 20 19]
reshape array:
 [[12 13  1 16  6]
 [ 8  6  4  3  1]
 [13 15  8 20 19]]
shape:
 (3, 5)
[[12 13  1  0  6]
 [ 0  6  4  3  1]
 [13 15  8  0 19]]


Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array

In [ ]:
import numpy as np
#array of size 4x3
array = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]], np.int32)

# Displaying the shape of the NumPy array (number of rows, number of columns)
print('shape of array:',array.shape)

# displaying the type of array
print('type of array:',type(array))

# Displaying the data type of the elements in the array
print('dataype:',array.dtype)

shape of array: (4, 3)
type of array: <class 'numpy.ndarray'>
dataype: int32


b.write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[3 -2]
[1 0]]

In [ ]:
import numpy as np

m = np.array([[3,-2],[1,0]])

# Display the original matrix 'm'
print("Original matrix:",m)

# Compute the eigenvalues and eigenvectors of the matrix 'm' using np.linalg.eig() function
e, v = np.linalg.eig(m)

print("Eigenvalues of the said matrix:", e)

print("Eigenvectors of the said matrix:", v)

Original matrix: [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix: [2. 1.]
Eigenvectors of the said matrix: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


c.Compute the sum of the diagonal element of a given array
  [[0 1 2]
  [3 4 5]]

In [ ]:
import numpy as np

# creating a 2x3 Numpy matrix
new_array = np.array([[0, 1, 2],
                    [3, 4, 5]])
print(new_array)

# Finding the diagonal elements of a matrix
diag = np.diagonal(new_array)
print("\nDiagonal elements are:",diag)

print("\nSum of Diagonal elements is:",sum(diag))

[[0 1 2]
 [3 4 5]]

Diagonal elements are: [0 4]

Sum of Diagonal elements is: 4


d.write a NumPy program to create a new shape to an array without changing its data

In [ ]:
import numpy as np
array=np.array([[1,2],[3,4],[5,6]])
print('original array:\n',array)
reshape=array.reshape(2,3)
print('reshape array:\n',reshape)
array1=np.array([[1,2,3],[4,5,6]])
print('original array1:\n',array1)
reshape1=array.reshape(3,2)
print('reshape array:\n',reshape1)
try:
    new_arr = array.reshape(3, 4)  # Attempt to reshape the array into an incompatible shape
    print("\nReshaped array:\n", new_arr)
except ValueError as e:
    print("\nError:", e)

original array:
 [[1 2]
 [3 4]
 [5 6]]
reshape array:
 [[1 2 3]
 [4 5 6]]
original array1:
 [[1 2 3]
 [4 5 6]]
reshape array:
 [[1 2]
 [3 4]
 [5 6]]

Error: cannot reshape array of size 6 into shape (3,4)
